/*
# Add barcode and QR code columns to equipment

1. Purpose
   Allow each equipment asset to have an auto-generated QR code and an optional
   user-entered barcode. When a technician scans a QR or barcode label on a piece
   of equipment, the app can look up the asset by either code.

2. New Columns
   - equipment.qr_code  (text, unique) — auto-generated QR identifier for the asset
   - equipment.barcode_id (text) — optional barcode string the user can enter if the
     physical asset already has a manufacturer barcode

3. Notes
   - qr_code is nullable so existing rows are not affected; new rows get a value
     generated by the app at creation time.
   - barcode_id is nullable and optional.
   - A unique index on qr_code prevents duplicates.
   - No RLS changes needed — equipment policies already exist.
*/

ALTER TABLE equipment
  ADD COLUMN IF NOT EXISTS qr_code text,
  ADD COLUMN IF NOT EXISTS barcode_id text;

CREATE UNIQUE INDEX IF NOT EXISTS idx_equipment_qr_code ON equipment (qr_code) WHERE qr_code IS NOT NULL;
